# Generated by Django 4.2 on 2026-06-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
