# Generated by Django 4.2 on 2026-07-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('', 'Computer Science'), ('', 'Information Technology'), ('', 'Software Engineering'), ('', 'Web Development'), ('', 'Data Science')], max_length=30),
        ),
    ]
