# Generated by Django 4.2 on 2026-07-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Software Engineering', 'Software Engineering'), ('Web Development', 'Web Development'), ('Data Science', 'Data Science')], max_length=30),
        ),
    ]
